### ISSUE TITLE
Outdoor calculator - assumption height

### ISSUE THREAD

**Issue by FedericoTartarini** [FedericoTartarini/covid-aerosol-transmission-estimator#10]
Explain why we are assuming a constant height.
height: 4.832,

**Comment by asitkm76** [comment]
When outdoors, we are in contact with earth's atmosphere. However, mixing still has some limitations. We assume that outdoors, air up to a height of about five meters can get mixed with air exhaled by people. Thus, for outdoors calculations, we assume a virtual room of height five meters and area as specified by you to understand infection risks, as we do for indoors.
