### ISSUE TITLE
write help effectiveness control measures

### ISSUE THREAD

**Issue by FedericoTartarini** [FedericoTartarini/covid-aerosol-transmission-estimator#13]
![image](https://user-images.githubusercontent.com/40018640/93707086-7106f380-fb5e-11ea-9c22-514aa37e2cc9.png)

**Comment by asitkm76** [comment]
Total effective ventilation with outdoor air (change title to this)

The calculations assume that outdoor air has no virus laden particles and hence, bringing outdoor air into a room will dilute such particles, reducing risks. In addition to actual outdoor air being brought in, portable air purifiers and a good filter in your air conditioning system also help by filtering out these particles. Taking all three measures together, we present in this output a qualitative rating of the amount of effective outdoor air ventilation your room receives.
The colour and word rating is based on the one[ used here](https://tinyurl.com/portableaircleanertool).
The word ratings correspond to the following effective air changes per hour, respectively:
Ideal (6 ACH or more)
Excellent (5-6 ACH)
Good (4-5 ACH)
Bare minimum (3-4 ACH)
Low (<3 ACH)
