### ISSUE TITLE
Write explanation decay rate virus and deposition on surfaces

### ISSUE THREAD

**Issue by FedericoTartarini** [FedericoTartarini/covid-aerosol-transmission-estimator#7]
We need to write some text about our assumption. We are currently using the following two values:
decayRateVirus: 9.3, // todo write about this assumption
depositionSurface: 0.3, // todo write about this assumption

**Comment by asitkm76** [comment]
Viruses, when outside their hosts, will gradually get inactivated. Several environmental parameters like temperature, humidity, UV index, determine this rate of inactivation or decay. For SARS-CoV-2, this parameter is not yet clearly known. This tool, based on Prof. Jimenez's work, uses a relatively conservative estimate which results in an additional loss rate of 0.63 per hour. For an estimate based on prevalent temperature, humidity and UV index, you can check the following [tool by DHS](https://www.dhs.gov/science-and-technology/sars-airborne-calculator). 

Cells of SARS-CoV-2 are contained within infective particles, exhaled by an infectious person. However, these particles will, gradually, settle down on floor/ground. This settling of particles thus leads to a further loss rate which we have approximated at 0.3 per hour. For an example of settling rate of differently sized particles indoors, you may have a look[ at this work](https://www.sciencedirect.com/science/article/abs/pii/S1352231002001577).

**Comment by FedericoTartarini** [comment]
Thank you so much for this, I am going to add this information to a link that people can access by clicking on the following header: Parameters related to COVID-19

Please let me know if you would like me to change that.

**Comment by asitkm76** [comment]
No, that name works.
